--
-- PostgreSQL database dump
--

\restrict B7h4UUfJWeKLGdIodREjiPNcfhpSiVeXG9RZarGZkKKw60lsgLfcehxaFCiSr76

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    end_time time(6) without time zone NOT NULL,
    start_time time(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    surface integer NOT NULL,
    total_price numeric(38,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    cleaner_id bigint NOT NULL,
    homer_id bigint NOT NULL,
    CONSTRAINT bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT bookings_surface_check CHECK ((surface >= 1))
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    description character varying(255),
    icon character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: categories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.categories_id_seq OWNED BY public.categories.id;


--
-- Name: cleaner_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cleaner_categories (
    cleaner_id bigint NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: cleaner_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cleaner_skills (
    cleaner_id bigint NOT NULL,
    skill_id bigint NOT NULL
);


--
-- Name: cleaners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cleaners (
    available boolean NOT NULL,
    bio character varying(2000),
    city character varying(255),
    experience_years integer,
    headline character varying(500),
    hourly_rate numeric(38,2),
    service_area character varying(255),
    id bigint NOT NULL,
    action_radius_km integer,
    price_per_sqm numeric(38,2),
    CONSTRAINT cleaners_experience_years_check CHECK (((experience_years <= 50) AND (experience_years >= 0)))
);


--
-- Name: homers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.homers (
    additional_info character varying(255),
    address character varying(255),
    city character varying(255),
    postal_code character varying(255),
    id bigint NOT NULL
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    comment character varying(1000) NOT NULL,
    created_at timestamp(6) without time zone,
    rating integer NOT NULL,
    reviewee_id bigint NOT NULL,
    reviewer_id bigint NOT NULL,
    CONSTRAINT reviews_rating_check CHECK (((rating <= 5) AND (rating >= 1)))
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: reviews_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reviews_id_seq OWNED BY public.reviews.id;


--
-- Name: skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skills (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: skills_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: skills_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.skills_id_seq OWNED BY public.skills.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255),
    profile_image character varying(255),
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    latitude double precision,
    longitude double precision,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['HOMER'::character varying, 'CLEANER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: categories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories ALTER COLUMN id SET DEFAULT nextval('public.categories_id_seq'::regclass);


--
-- Name: reviews id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews ALTER COLUMN id SET DEFAULT nextval('public.reviews_id_seq'::regclass);


--
-- Name: skills id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills ALTER COLUMN id SET DEFAULT nextval('public.skills_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: cleaner_categories cleaner_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cleaner_categories
    ADD CONSTRAINT cleaner_categories_pkey PRIMARY KEY (cleaner_id, category_id);


--
-- Name: cleaner_skills cleaner_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cleaner_skills
    ADD CONSTRAINT cleaner_skills_pkey PRIMARY KEY (cleaner_id, skill_id);


--
-- Name: cleaners cleaners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cleaners
    ADD CONSTRAINT cleaners_pkey PRIMARY KEY (id);


--
-- Name: homers homers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.homers
    ADD CONSTRAINT homers_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);


--
-- Name: users uk_6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: skills uk_85woe63nu9klkk9fa73vf0jd0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT uk_85woe63nu9klkk9fa73vf0jd0 UNIQUE (name);


--
-- Name: categories uk_t8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT uk_t8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: reviews fk1sjw2c8j34ew366vfqxergp0b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk1sjw2c8j34ew366vfqxergp0b FOREIGN KEY (reviewee_id) REFERENCES public.users(id);


--
-- Name: cleaner_categories fk2cpauf2k6qwmwf5ql3p2rv09p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cleaner_categories
    ADD CONSTRAINT fk2cpauf2k6qwmwf5ql3p2rv09p FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- Name: cleaner_skills fk755e40sd5t252414te8esd8mj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cleaner_skills
    ADD CONSTRAINT fk755e40sd5t252414te8esd8mj FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- Name: cleaner_categories fkb6sa3tc99hmr4jiv4efol6wkf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cleaner_categories
    ADD CONSTRAINT fkb6sa3tc99hmr4jiv4efol6wkf FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: cleaners fkch6rdhm9ecsip5h83gk790lg5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cleaners
    ADD CONSTRAINT fkch6rdhm9ecsip5h83gk790lg5 FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: reviews fkd1isgfajhtdl8mgg29up6mofi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkd1isgfajhtdl8mgg29up6mofi FOREIGN KEY (reviewer_id) REFERENCES public.users(id);


--
-- Name: cleaner_skills fkdvor51eq9mt9qxq9y3xvl2fba; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cleaner_skills
    ADD CONSTRAINT fkdvor51eq9mt9qxq9y3xvl2fba FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: homers fkf79k4nf1cocejad5bu1gby31w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.homers
    ADD CONSTRAINT fkf79k4nf1cocejad5bu1gby31w FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: bookings fkjxnl55f1uql9dxqpowr1k51xc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkjxnl55f1uql9dxqpowr1k51xc FOREIGN KEY (homer_id) REFERENCES public.homers(id);


--
-- Name: bookings fkteq1vioagvk85r6s20tfjp00u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkteq1vioagvk85r6s20tfjp00u FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- PostgreSQL database dump complete
--

\unrestrict B7h4UUfJWeKLGdIodREjiPNcfhpSiVeXG9RZarGZkKKw60lsgLfcehxaFCiSr76

